- src/main/java/com/gdsc_knu/official_homepage/annotation/TokenMember.java
- src/main/java/com/gdsc_knu/official_homepage/annotation/TokenMemberResolver.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/JwtTokenProvider.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/JwtTokenValidator.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/redis/JwtMemberDetail.java
- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
- src/main/java/com/gdsc_knu/official_homepage/controller/JwtTestController.java
Resolver를 사용하여 jwt에서 멤버 정보를 가져옵니다.
---
---
---
> Feat/issue #7

- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
WebConfig 수정으로 쿠키 cors 허용
---
---
---
> Fix: 쿠키 cors 허용

- src/main/java/com/gdsc_knu/official_homepage/annotation/TokenMemberResolver.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/filter/JwtFilter.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtMemberDetail.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtTokenProvider.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtTokenValidator.java
- src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
- src/main/java/com/gdsc_knu/official_homepage/controller/JwtTestController.java
- src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
- src/main/java/com/gdsc_knu/official_homepage/oauth/OAuthService.java
1. 쿠키 cors 에러를 해결하기 위해 header를 추가했습니다.
2. 이전 pr에서 논의 되었던 authentication 패키지 구조를 변경했습니다.
---
---
---
> 쿠키 cors 관련 재수정

- .github/workflows/deploy.yml
- docker-compose.yml
- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
- src/main/java/com/gdsc_knu/official_homepage/oauth/OAuthService.java
docker-compose 워크플로 수정
---
---
---
> Feat/issue #30

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
- src/main/java/com/gdsc_knu/official_homepage/controller/AuthController.java
- src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/oauth/AuthorizationCode.java
- src/main/java/com/gdsc_knu/official_homepage/dto/oauth/Provider.java
- src/main/java/com/gdsc_knu/official_homepage/oauth/OAuthService.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
- test/deploy 워크플로 분리
- rest api 명세 수정
---
---
---
closes #24
> Feat/issue #24

- src/main/java/com/gdsc_knu/official_homepage/controller/AuthController.java
- src/main/java/com/gdsc_knu/official_homepage/controller/RoleController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/role/UserRoleRequest.java
- src/main/java/com/gdsc_knu/official_homepage/entity/Member.java
- src/main/java/com/gdsc_knu/official_homepage/service/PermissionSerivce.java
- 멤버 승인 API 구현
---
---
---
closes #26
> Feat/issue #26

- src/main/java/com/gdsc_knu/official_homepage/dto/application/ApplicationAnswerDTO.java
- src/main/java/com/gdsc_knu/official_homepage/dto/application/ApplicationRequest.java
- src/main/java/com/gdsc_knu/official_homepage/dto/application/ApplicationResponse.java
- src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
- src/main/java/com/gdsc_knu/official_homepage/entity/application/ApplicationAnswer.java
- src/main/java/com/gdsc_knu/official_homepage/repository/ApplicationRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationServiceImpl.java
지원서에 문항 별 답변 추가
---
---
---
closes #28
> Feat/issue #28

- src/main/java/com/gdsc_knu/official_homepage/entity/enumeration/ApplicationStatus.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/repository/ApplicationRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationServiceImpl.java
1. applicationStatus 합격, 탈락 상태 추가
2. 각종 예외 처리 대응
---
---
---
closes #34
> Fix/issue #34

- src/main/java/com/gdsc_knu/official_homepage/controller/ApplicationController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/application/ApplicationRequest.java
- src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
- src/main/java/com/gdsc_knu/official_homepage/exception/CustomException.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/exception/GlobalExceptionHandler.java
- src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationService.java
- src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationServiceImpl.java
1. 지원서 작성 시 로그인(token) 요구
2. 지원서 관련 내부 로직 수정
3. 지원서 예외 처리 보강 및 포맷 통일
---
---
---
closes #36
> Feat/issue #36

- src/main/java/com/gdsc_knu/official_homepage/dto/member/MemberRequest.java
- src/main/java/com/gdsc_knu/official_homepage/entity/Member.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
> Fix: 회원가입시 직렬 정보 제외

- .github/workflows/test.yml
- src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/PagingResponse.java
- src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/AdminApplicationRes.java
- src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationStatisticType.java
- src/main/java/com/gdsc_knu/official_homepage/dto/auth/LoginRequest.java
- src/main/java/com/gdsc_knu/official_homepage/dto/auth/SignupRequest.java
- src/main/java/com/gdsc_knu/official_homepage/dto/member/MemberRequest.java
- src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
- src/main/java/com/gdsc_knu/official_homepage/repository/ApplicationRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
- 서류 확인 옵션별 페이징 기능 구현
---
---
---
closes #43
> Feat/issue #43

- src/main/java/com/gdsc_knu/official_homepage/annotation/TokenMemberResolver.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/filter/JwtFilter.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtClaims.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtMemberDetail.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtTokenProvider.java
- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtTokenValidator.java
- src/main/java/com/gdsc_knu/official_homepage/controller/JwtTestController.java
- src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
- src/main/java/com/gdsc_knu/official_homepage/oauth/OAuthService.java
- jwt payload에 id, email, role 정보를 포함하도록 수정함.
---
- 필터에서 걸리는 예외 catch 에서 핸들링 할 수 있도록 수정 필요
---
---
#50
> Feat/issue #50

- src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
- src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminMemberStatusController.java
- src/main/java/com/gdsc_knu/official_homepage/repository/ApplicationRepository.java
- src/main/java/com/gdsc_knu/official_homepage/repository/MemberRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminMemberStatusService.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminMemberStatusServiceImpl.java
- 키워드 검색 기능 추가 (서류 확인, 상태 조정)
---
- Jpa의 Containing을 이용해 구현하였습니다.
- 한 글자 단위로 검색되며 두개이상의 글자로 조회할시 연속하여 일치하는 것만 반환합니다.
---
---
closes #64
> Feat/issue #64

- build.gradle
- src/main/java/com/gdsc_knu/official_homepage/config/RetryConfig.java
- src/main/java/com/gdsc_knu/official_homepage/config/S3Config.java
- src/main/java/com/gdsc_knu/official_homepage/controller/RoleController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/member/MemberRequest.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
- src/main/java/com/gdsc_knu/official_homepage/service/PermissionSerivce.java
- src/main/java/com/gdsc_knu/official_homepage/service/S3Service.java
- src/main/java/com/gdsc_knu/official_homepage/service/fileupload/S3FileUploader.java
- AmazonS3client -> AmazonS3 로 수정
- 사용자 정보 수정 중 프로필 이미지는 null 허용하도록 수정
---
---
---
#61
> Feat/issue #61

- src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminTeamController.java
- src/main/java/com/gdsc_knu/official_homepage/entity/Team.java
- src/main/java/com/gdsc_knu/official_homepage/repository/MemberTeamRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamService.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamServiceImpl.java
1. AdminTeam 삭제 기능 구현
2. teamId 변수 명을 parent, sub, team으로 명확히 구분
3. 팀 이동 검증 로직 추가(다른 부모 팀으로 이동 불가)
---
---
---
closes #69
> Feat/issue #69

- src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationServiceImpl.java
1. ApplicationService 주석 추가
---
---
---
closes #75
> Comment: ApplicationService 메서드에 주석 추가

- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
> Fix: allow origin 추가

- src/main/java/com/gdsc_knu/official_homepage/controller/TeamController.java
- src/main/java/com/gdsc_knu/official_homepage/repository/MemberTeamRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/TeamService.java
> Feat: 가장 최근 생성된 팀의 팀원 조회

- src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/admin/memberStatus/AdminMemberResponse.java
- src/main/java/com/gdsc_knu/official_homepage/dto/member/TeamInfoResponse.java
- src/main/java/com/gdsc_knu/official_homepage/dto/oauth/GoogleUserInfo.java
- src/main/java/com/gdsc_knu/official_homepage/dto/team/TeamResponse.java
- src/main/java/com/gdsc_knu/official_homepage/entity/Member.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoService.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
- 사용자 정보 수정 api spec수정
- 권한 변경 편의 메서드 구현
#109 에서 분기한거라 rebase merge 필요
- close #104
> Feat/issue #104

- .github/workflows/deploy-dev.yml
- .github/workflows/test-dev.yml
- .gitignore
- src/main/resources/application-auth.yml
- src/main/resources/application-db.yml
- src/main/resources/application-doc.yml
- src/main/resources/application.yml
- src/test/java/com/gdsc_knu/official_homepage/OfficialHomepageApplicationTests.java
- yml 파일 분리 규칙 수정
- docker 환경변수 주입으로 변경
- deploy 테스트를 위해 dev브랜치 머지
- #112
> Refac/issue #112

- src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
- src/main/java/com/gdsc_knu/official_homepage/controller/post/PostController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/post/PostRequest.java
- src/main/java/com/gdsc_knu/official_homepage/dto/post/PostResponse.java
- src/main/java/com/gdsc_knu/official_homepage/entity/post/Post.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/repository/PostQueryFactory.java
- src/main/java/com/gdsc_knu/official_homepage/repository/PostQueryFactoryImpl.java
- src/main/java/com/gdsc_knu/official_homepage/repository/PostRepository.java
- src/main/java/com/gdsc_knu/official_homepage/service/post/PostService.java
- src/main/java/com/gdsc_knu/official_homepage/service/post/PostServiceImpl.java
테크블로그 게시글 CRUD
- 기본적으로 게시글 조회는 모든 유저가 가능하며, SAVED된 글만 조회 가능합니다. 
- 임시 저장 글은 작성자만 조회 가능합니다.
- 수정 시 필요한 정보만 프론트에 넘겨주기 위해 PostResponse.Modify를 사용했습니다.
- 인기글 조회 서비스 관련 코드는 인터페이스로 통합하여 Conflict를 해결했습니다. 혹시 로직을 제가 잘못 통합했다면 말씀해주세요.
- PostResponse.Main의 summary를 subTitle로 교체했습니다. 디자인에 부제목 지정하는 것이 있어 부제목으로 보여주는게 맞는 것 같습니다.
- 댓글 카운트 방식에 대한 고민이 필요합니다
- 현재는 간단하게 요청 시 마다 직접 commentList의 size를 계산하는데, 이를 댓글 작성마다 업데이트 해야 할지 고민해봐야 합니다.
- 현재 방식은 간단하게 구현이 되고 추가적인 로직이나 연산이 필요 없지만, 요청이 한꺼번에 오면 일관성에 문제가 생길 수 있습니다.
- 매번 업데이트 하는 방식은 일관성이 보장되지만, 추가 로직이나 계속적인 DB 연산이 필요합니다.
- 의견 말씀해주세요!
- 좋아요, 검색 기능은 시험이 끝나고 추후 개발 예정입니다...
- close #115
> 테크 블로그 게시글

- src/main/java/com/gdsc_knu/official_homepage/entity/post/Comment.java
- src/test/java/com/gdsc_knu/official_homepage/member/MemberServiceTest.java
- src/test/java/com/gdsc_knu/official_homepage/post/comment/CommentServiceTest.java
- src/test/java/com/gdsc_knu/official_homepage/post/comment/PostServiceTest.java
- src/test/java/com/gdsc_knu/official_homepage/team/AdminTeamServiceTest.java
- 게시글, 댓글
- 게시글, 좋아요
- 팀, 멤버
- 상위팀, 하위팀
연관관계 관련된 테스트 작성
- close #132
> 양방향 연관관계 관련 테스트 코드 작성

- src/main/java/com/gdsc_knu/official_homepage/exception/GlobalExceptionHandler.java
- src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationQueryFactoryImpl.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
- 지원서 목록 정렬 조건 추가
- 마지막 커밋은 디스코드 CustomException 알림을 prod만 활성화 해야하는데 테스트한다고 local로 했다가 수정하는걸 깜박했습니다.
최신순으로 modified_at을 이용하여 정렬하려 했으나, 해당 칼럼에 인덱스가 없고, 어쩌피 나중에 기수 필드 추가되면 쿼리 수정해야할 것 같아서 id로 내림차순 정렬했습니다.
- close #139
> 지원서 목록 정렬 조건 추가

- src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtValidator.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/service/MemberService.java
- src/test/java/com/gdsc_knu/official_homepage/member/service/MemberServiceTest.java
- 중복 회원 오류메세지 수정
- ErrorCode 중복 code 변경
- close #143
> 중복 회원 오류메세지 수정

- src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/AdminApplicationRequest.java
- src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/AdminApplicationResponse.java
- src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
- src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
- src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
- src/test/java/com/gdsc_knu/official_homepage/application/ApplicationTestEntityFactory.java
- src/test/java/com/gdsc_knu/official_homepage/application/domain/ApplicationTest.java
- src/test/java/com/gdsc_knu/official_homepage/application/service/AdminApplicationServiceTest.java
낙관적 락을 이용하여 지원서 메모 업데이트 동시성 문제 해결
- close #147
> 지원서 메모 동시성 제어

- .github/workflows/deploy_manual.yml
수동 workflow 파일 수정
- close #162
> Feat: 수동 workflow 수정

- src/main/java/com/gdsc_knu/official_homepage/config/SwaggerConfig.java
- src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
- src/main/java/com/gdsc_knu/official_homepage/controller/post/PostController.java
- src/main/java/com/gdsc_knu/official_homepage/dto/post/PostResponse.java
- src/main/java/com/gdsc_knu/official_homepage/service/post/PostService.java
- src/main/java/com/gdsc_knu/official_homepage/service/post/PostServiceImpl.java
- src/main/resources/application.yml
- 주석 처리 되어있던 임시글 수정 기능을 복구했습니다
- close
> 임시글 수정 API 복구
