src/main/java/com/gdsc_knu/official_homepage/annotation/TokenMemberResolver.java
src/main/java/com/gdsc_knu/official_homepage/authentication/JwtFilter.java
src/main/java/com/gdsc_knu/official_homepage/authentication/redis/JwtMemberDetail.java
src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
src/main/java/com/gdsc_knu/official_homepage/config/SwaggerConfig.java
src/main/java/com/gdsc_knu/official_homepage/controller/AuthController.java
src/main/java/com/gdsc_knu/official_homepage/controller/JwtTestController.java
src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
src/main/java/com/gdsc_knu/official_homepage/dto/SignupRequest.java
src/main/java/com/gdsc_knu/official_homepage/dto/member/MemberInfoAdd.java
src/main/java/com/gdsc_knu/official_homepage/dto/oauth/GoogleUserInfo.java
src/main/java/com/gdsc_knu/official_homepage/entity/Member.java
src/main/java/com/gdsc_knu/official_homepage/entity/enumeration/Role.java
src/main/java/com/gdsc_knu/official_homepage/oauth/OAuthService.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoService.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java

- JwtFilter 를 만들어 인증과 인가 작업 수행
- Role 에 따른 권한 부여
- 인증이 필요한 요청에 대해 TokenMember를 이용해 사용자 정보 가져오도록 수정
---
1. JwtMemberDetail 클래스에 UserDetails 상속하도록 수정해서 Authentication객체에서 사용자 정보로 사용하도록 구현했는데 이대로 할지 아니면 UserDetails을 상속하는 다른 클래스를 한개 더 만들지 논의 필요
2. 리졸버, 필터에서 2번 인증을 진행하는 문제 (필터에서 jwtTokenValidator를 이용하지 않고 페이로드에서 이메일만 가져오도록 수정하는게 맞는 방향인지 논의 필요)
3. JwtMemberDetail 클래스가 redis 폴더에 위치 /  authentication 폴더에 JwtFilter(인가 역할도 함)클래스가 위치  -> (어디로 옮겨야  할지 모르겠네요...)
---
---
closes #15

Feat/issue #15

---

src/main/java/com/gdsc_knu/official_homepage/entity/enumeration/Track.java

트랙에 누락된 디자이너 추가
---
4기부터는 디자이너도 GDSC 모집 시에 동시 선발 예정
---
---

Fix: track enum에 디자이너 추가

---

src/main/java/com/gdsc_knu/official_homepage/entity/Member.java

기본 값(255자)으로 적용되어 있던 introduction field를 500자로 알맞게 수정
---
---
---
closes #47

Fix: 자기소개 필드 길이 500자로 변경

---

src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminTeamController.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminMemberResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminTeamChangeRequest.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminTeamCreateRequest.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminTeamInfoResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminTeamResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/member/TeamInfoResponse.java
src/main/java/com/gdsc_knu/official_homepage/entity/MemberTeam.java
src/main/java/com/gdsc_knu/official_homepage/entity/Team.java
src/main/java/com/gdsc_knu/official_homepage/repository/MemberRepository.java
src/main/java/com/gdsc_knu/official_homepage/repository/MemberTeamRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamService.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamServiceImpl.java

1. 모든 팀 조회 기능 구현
2. 팀별 사용자 조회 기능 구현
3. 새로운 팀(부모 팀) 생성 기능 구현
4. 서브팀(스터디 BE - 1팀, 스터디 BE - 2팀, ...) 생성 기능 구현
5. 팀원 이동 기능 구현
---
- 모든 팀 조회시 부모 팀이 리스트로 조회 되고, 서브 팀은 부모 팀의 하위 리스트로 조회 됩니다.
- 디자인에 맞게 어드민 페이지에서 멤버 조회 시 이름, 학번, 프로필 이미지 url만 반환합니다.
- 최초 생성 시에는 부모 팀에 직렬에 맞게 멤버가 소속되며, 이후 서브 팀으로 옮겨 정상적 팀 배치가 가능합니다.
---
swagger @Operation(description="...") 작성 시 줄바꿈 두개 해야 줄바꿈이 되어 출력되는데 저만 그런걸까요...?
---
closes #54

Feat/issue #54

---

src/main/java/com/gdsc_knu/official_homepage/authentication/jwt/JwtProvider.java
src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationTrackType.java
src/main/java/com/gdsc_knu/official_homepage/repository/ApplicationRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java

- 엑세스 토큰 유효시간 1일로 복구
- 직렬별로 최종제출된 지원서 개수 카운트 기능 구현
---
- map<직렬, 개수>의 형태로 응답을 구성하여 dto클래스를 따로 두지 않음.
---
---
closes #84

Feat/issue #84

---

src/main/java/com/gdsc_knu/official_homepage/controller/TeamController.java
src/main/java/com/gdsc_knu/official_homepage/dto/team/TeamResponse.java
src/main/java/com/gdsc_knu/official_homepage/repository/MemberTeamRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/TeamService.java

- 일반 사용자의 팀원 정보 조회 기능 구현
- 어드민 API의 팀원 조회는 부모팀으로 조회 미배치된 사용자를 모두 반환하기에 기존 코드 재활용하지 않고 새로운 메소드 작성
- 추후 공통 부분은 하나의 메소드로 합치는 방법도 생각해 보겠습니다.
- member team repository에서 teamId로 가져올때 member를 조인해서 가져오는 jpql 코드가 2개로 중복되는데, projection dto 를 따로 정의하여 `findAllByTeamId` `findMembersByTeamId` 두 함수를 하나로 쓸 수 있도록 수정하면 좋을 것 같습니다.
- #97

일반 사용자의 팀원 정보 조회 (#97)

---

src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamServiceImpl.java

마이페이지 부모 팀 노출, 어드민페이지 팀 배치 시 정식 멤버가 아닌 회원 반환 오류를 수정했습니다.
- close #99

[Fix] 팀 배치 오류 관련 수정

---

src/main/java/com/gdsc_knu/official_homepage/controller/MemberController.java
src/main/java/com/gdsc_knu/official_homepage/controller/TeamController.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/memberStatus/AdminMemberResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/team/AdminTeamResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/member/TeamInfoResponse.java
src/main/java/com/gdsc_knu/official_homepage/entity/Team.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoService.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminTeamServiceImpl.java

- 멤버 소속 팀 리스트 조회 기능 구현 
- 팀 페이지 url 컬럼 및 관련 로직 삭제
- 일단 API를 MemberController에 위치 시켰는데, TeamController가 더 적절할 수도 있을 것 같습니다. 의견 부탁드립니다.
- close #102

멤버 소속 팀 리스트 조회, 팀 페이지 url 컬럼 삭제

---

src/main/java/com/gdsc_knu/official_homepage/controller/TeamController.java
src/main/java/com/gdsc_knu/official_homepage/service/TeamService.java

- 팀원 조회 시 id=0 으로 조회할 경우 트랜젝션 시작 전 바로 종료
- #97

Fix: id=0 으로 조회할 경우 바로 종료

---

src/main/java/com/gdsc_knu/official_homepage/dto/admin/memberStatus/AdminMemberResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/member/TeamInfoResponse.java
src/main/java/com/gdsc_knu/official_homepage/entity/Member.java
src/main/java/com/gdsc_knu/official_homepage/service/MemberInfoServiceImpl.java

- 부모팀 체크 공통 로직을 추출하여 반복되는 실수를 방지한다.
- member 엔티티에 배정이 완료된 team만 조회하는 getter 메소드를 정의한다
- 외부에서는 정의한 getter 로 team정보에 접근한다.
- close #109

Refac/issue #109

---

src/main/java/com/gdsc_knu/official_homepage/entity/post/Comment.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/Post.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/enumeration/Category.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/enumeration/PostStatus.java

- 게시글 엔티티 작성
- 댓글 엔티티 작성
- ui 에 게시글 작성자가 없어서 게시글에는 작성자 관련된 비정규화를 하지 않았는데, 작성자 정보가 필요하면 해당 필드는 post엔티티에 중복으로 두는 것도 join을 줄이기 위해 좋을 것 같습니다.
- 좋아요 기능이 일단 우선 순위가 낮다고 판단하여 정수형의 likeCount 필드만 뒀는데, 좋아요 기능 구현할 때 사용자와 매치하기 위한 테이블이 추가로 필요할 것 같습니다.
- 게시글은 좋아요, 댓글 수 등등으로 수정될 수 있고, 최초로 레코드가 생긴시점이 출간일자가 되는게 아니라 상태가 'SAVED'로 바뀌는 순간이 출간일자가 되기 때문에 BaseTimeEntity를 상속하지 않았습니다.
- close #116

테크블로그 엔티티 작성

---

.github/workflows/test-dev.yml
src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
src/main/java/com/gdsc_knu/official_homepage/controller/post/CommentController.java
src/main/java/com/gdsc_knu/official_homepage/dto/PagingResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/AccessModel.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/CommentRequest.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/CommentResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/PermissionModel.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/Comment.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/Post.java
src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
src/main/java/com/gdsc_knu/official_homepage/repository/CommentRepository.java
src/main/java/com/gdsc_knu/official_homepage/repository/PostRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/post/CommentService.java
src/test/java/com/gdsc_knu/official_homepage/service/post/CommentServiceTest.java

- 댓글 작성, 조회, 수정, 삭제
- 게시글 조회 관련 api는 WHITE LIST에 등록하여 로그인없이 조회할 수 있도록 하였습니다.
- 이때 수정, 삭제 권한을 함께 알려줘야 해서 로그인하지 않은 사용자에 대해서는 id=0을 임시로 부여하였는데 id 생성방식에 종속적이게 되는 것 같아 좋은 설계는 아니라고 생각합니다. 
- 해당 메서드를 인터페이스로 만들고 로그인 여부에 따라 구현체를 달리할 계획이긴 한데, 우선 프론트개발을 위해 지금 상태에서 PR 올립니다
- 외에도 다른 좋은 방법이 있다면 알려주세요 !
- 페이징 처리할때 무한스크롤의 경우 현재 페이지와 전체 페이지 수를 계산할 필요가 없다고 판단하여 `withoutCountFrom`이라는 메서드를 만들었습니다. 
- close #118

게시글 댓글 CRUD

---

src/main/java/com/gdsc_knu/official_homepage/OfficialHomepageApplication.java
src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
src/main/java/com/gdsc_knu/official_homepage/controller/post/PostController.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/PostResponse.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/Post.java
src/main/java/com/gdsc_knu/official_homepage/repository/PostQueryFactory.java
src/main/java/com/gdsc_knu/official_homepage/repository/PostQueryFactoryImpl.java
src/main/java/com/gdsc_knu/official_homepage/repository/PostRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/post/PostService.java

- 게시글 인기순 조회
- 인기 게시글의 경우 요청마다 매번 탐색할 필요가 없을 것 같아서 카테고리별로 캐싱해두었고, 스케줄러를 통해 매일 자정 캐싱된 데이터를 지우도록 했습니다.
- 혹시 매번 업데이트되어야 한다면 좋아요 등록 API에서 백그라운드 작업으로 인기글을 업데이트하는 방법을 고려해보겠습니다.
- 외에도 다른 좋은방법이 있다면 알려주세요 !
- Post 엔티티에 enum을 숫자로 저장하고 있는 것을 발견하여 수정했습니다. (ddl update 필요)
- 📢 게시글 조회와 관련된 것들은 전부 white list에 들어갈 것 같은데 하실때 '/api/post/**'의 GET 메서드로 와일드카드로 나타내도 좋을 것 같습니다.
- close #120

Feat/issue #120

---

.gitignore
src/main/java/com/gdsc_knu/official_homepage/controller/post/PostController.java
src/main/java/com/gdsc_knu/official_homepage/dto/fileupload/FileUploadRequest.java
src/main/java/com/gdsc_knu/official_homepage/dto/fileupload/FileUploadResponse.java
src/main/java/com/gdsc_knu/official_homepage/service/fileupload/FileUploader.java
src/main/java/com/gdsc_knu/official_homepage/service/fileupload/LocalUploader.java
src/main/java/com/gdsc_knu/official_homepage/service/fileupload/S3Uploader.java
src/main/resources/application-db.yml

- 이미지 저장 api 구현
- 기존 S3Service를 없애고 인터페이스로 두어 로컬환경과 운영환경의 이미지 저장소를 분리했습니다.
- 로컬 이미지 저장소 경로 -> .env에 업데이트했는데, 각자 환경에 맞는 경로로 재설정하면 됩니다. !
- close #123

Feat: 이미지 업로드

---

src/main/java/com/gdsc_knu/official_homepage/config/TxTemplateConfig.java
src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
src/main/java/com/gdsc_knu/official_homepage/entity/enumeration/Track.java
src/main/java/com/gdsc_knu/official_homepage/repository/CommentRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/MailService.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
src/test/java/com/gdsc_knu/official_homepage/repository/CommentRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/repository/application/AdminApplicationRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/repository/post/CommentRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationTest.java
src/test/java/com/gdsc_knu/official_homepage/service/post/CommentServiceTest.java

- 지원 현황 조회 테스트 코드 작성
- 트랙별 지원 개수 테스트 코드 작성
- 이 과정에서 처음 로그인한 사용자는 track 을  UNDEFINED로 두기로 수정했는데, 해당 필드가 응답에 포함되는 문제를 발견하고 `getValidTrack`을 정의하여 UNDEFINED는 제외하고 가져오도록 수정했습니다.
- 임시저장된 지원서를 합/불 처리 하지 못하는지 테스트 코드 작성
- 지원서 상태를 변경하는 메서드를 Application 클래스로 옮겨 객체지향적으로 수정
- 'transaction template` 빈 등록하여 재사용하도록 수정
- 댓글 등록 시 그룹이 올바르게 설정되는지 테스트 추가
- 댓글 페이징 조회시 순서가 올바른지 조회 쿼리 테스트 추가 
- 기존 댓글 관련 테스트 코드 리팩토링
- close #88

지원서 조회 / 게시글 댓글 테스트 코드 작성

---

src/main/java/com/gdsc_knu/official_homepage/controller/post/PostController.java
src/main/java/com/gdsc_knu/official_homepage/dto/post/PostResponse.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/Post.java
src/main/java/com/gdsc_knu/official_homepage/entity/post/PostLike.java
src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
src/main/java/com/gdsc_knu/official_homepage/repository/PostLikeRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/post/CommentService.java
src/main/java/com/gdsc_knu/official_homepage/service/post/PostService.java
src/main/java/com/gdsc_knu/official_homepage/service/post/PostServiceImpl.java

1. commetCount에 댓글 개수를 댓글 생성/삭제마다 갱신해 저장하도록 바꾸었습니다.
2. 게시글에 좋아요/좋아요 취소가 가능합니다.
3. 게시글 Detail을 반환할 때 좋아요 여부를 추가로 반환합니다.
- close #125

테크블로그 게시글 좋아요 기능 개발

---

src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationStatisticType.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationTrackType.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationQueryFactory.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationQueryFactoryImpl.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
src/test/java/com/gdsc_knu/official_homepage/application/ApplicationTestEntityFactory.java
src/test/java/com/gdsc_knu/official_homepage/application/repository/AdminApplicationRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/application/service/AdminApplicationServiceTest.java

- 지원서 목록 페이징 조회에서 count 쿼리에 기수 필터링 빠진거 추가
- 직렬별 통계 쿼리에 기수 필터링 추가
- 지원현황 통계 쿼리에 기수 필터링 추가
- 지원현황에 이전 api랑 호환성 지켜지도록 서류 합격 필드 한개만 추가했습니다.
- 이전에 수정하신 지원서 목록 테스트 코드에서 기수를 여러개 생성할 필요없는 부분에 대해서는 1개만 생성하도록 수정했습니다.
- close #153

어드민 - 지원서 count 쿼리에 기수 필터링 적용

---

src/main/java/com/gdsc_knu/official_homepage/controller/admin/AdminApplicationController.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/AdminApplicationResponse.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationStatisticType.java
src/main/java/com/gdsc_knu/official_homepage/dto/admin/application/ApplicationTrackType.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationQueryFactory.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationQueryFactoryImpl.java
src/main/java/com/gdsc_knu/official_homepage/repository/application/ApplicationRepository.java
src/main/java/com/gdsc_knu/official_homepage/service/admin/AdminApplicationService.java
src/test/java/com/gdsc_knu/official_homepage/application/ApplicationTestEntityFactory.java
src/test/java/com/gdsc_knu/official_homepage/application/repository/AdminApplicationRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/application/service/AdminApplicationServiceTest.java

- 지원서 목록 페이징 조회에서 count 쿼리에 기수 필터링 빠진거 추가
- 직렬별 통계 쿼리에 기수 필터링 추가
- 지원현황 통계 쿼리에 기수 필터링 추가
- 지원현황에 이전 api랑 호환성 지켜지도록 서류 합격 필드 한개만 추가했습니다.
- 이전에 수정하신 지원서 목록 테스트 코드에서 기수를 여러개 생성할 필요없는 부분에 대해서는 1개만 생성하도록 수정했습니다.
- close #153

지원서 count 쿼리에 기수 필터링 적용

---

src/main/java/com/gdsc_knu/official_homepage/entity/application/Application.java
src/main/java/com/gdsc_knu/official_homepage/exception/ErrorCode.java
src/main/java/com/gdsc_knu/official_homepage/service/application/ApplicationServiceImpl.java
src/test/java/com/gdsc_knu/official_homepage/application/ApplicationTestEntityFactory.java
src/test/java/com/gdsc_knu/official_homepage/application/ApplicationTestFactory.java
src/test/java/com/gdsc_knu/official_homepage/application/domain/ApplicationTest.java
src/test/java/com/gdsc_knu/official_homepage/application/repository/AdminApplicationRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/application/service/AdminApplicationServiceTest.java
src/test/java/com/gdsc_knu/official_homepage/application/service/ApplicationServiceTest.java
src/test/java/com/gdsc_knu/official_homepage/member/MemberTestEntityFactory.java
src/test/java/com/gdsc_knu/official_homepage/member/domain/MemberTest.java
src/test/java/com/gdsc_knu/official_homepage/member/repository/MemberRepositoryTest.java
src/test/java/com/gdsc_knu/official_homepage/member/service/MemberServiceTest.java
src/test/java/com/gdsc_knu/official_homepage/team/TeamTestEntityFactory.java
src/test/java/com/gdsc_knu/official_homepage/team/service/AdminTeamServiceTest.java

- 지원서 관련 테스트 코드 작성
- 일반 예외 처리에서 CustomException 처리로 변경
- 테스트 공통 메서드 추출
- 멤버 테스트 공통 메서드를 오버로딩해서 추출했습니다. 틀렸거나, 좀 더 나은 구조가 있다면 말씀해주세요(7bb7c6ec3f5839371c1ea1d22c46e2f5eaebc63b)
- 저번에도 에러가 터져서 Application 생성자에 ApplicationAnswer와 연관관계 누락된걸 수정해뒀는데... 어디서 다시 되돌아간지 모르겠네요... 다시 돌려뒀습니다.(babf756ce04869cd5e4f66c2e18bfa8b90a5cf5e)
- close #152

지원서 테스트 코드 추가 및 오류 수정

---

src/main/java/com/gdsc_knu/official_homepage/config/SecurityConfig.java
src/main/java/com/gdsc_knu/official_homepage/config/WebConfig.java
src/main/resources/application.yml

- 자신의 서버로 요청을 보내는 경우 서버의 도메인이 CORS에 의해 차단되는 오류를 수정
- (타임리프 (세미나 출석 알림) 사용 시 본 서버로 post 요청을 보낼때 오류 발생)
- 서버의 ip와 도메인을 .env 에 업데이트 했습니다.
- close #159

타임리프 사용 API CORS 수정
